xbterminal/api/urls.py
from django.conf.urls import include, url
from rest_framework import routers

from api import views_v1, views_v2, renderers


api_v1_urls = [
    url(r'^merchant/?$',
        views_v1.MerchantView.as_view(),
        name='merchant'),
    url(r'^devices/?$',
        views_v1.DevicesView.as_view(),
        name='devices'),
    url(r'^devices/(?P<key>[0-9a-zA-Z]{8,32})/?$',
        views_v1.device,
        name='device'),

    url(r'^payments/init/?$',
        views_v1.PaymentInitView.as_view(),
        name='payment_init'),
    url(r'^payments/(?P<uid>[0-9a-zA-Z]{6,32})/request/?$',
        views_v1.PaymentRequestView.as_view(),
        name='payment_request'),
    url(r'^payments/(?P<uid>[0-9a-zA-Z]{6,32})/response/?$',
        views_v1.PaymentResponseView.as_view(),
        name='payment_response'),
    url(r'^payments/(?P<uid>[0-9a-zA-Z]{6,32})/check/?$',
        views_v1.PaymentCheckView.as_view(),
        name='payment_check'),

    url(r'^receipts/(?P<uid>[0-9a-zA-Z]{6,32})/?$',
        views_v1.ReceiptView.as_view(),
        name='receipt'),
]

short_urls = [
    url(r'^pr/(?P<uid>[0-9a-zA-Z]{6,32})/?$',
        views_v1.PaymentRequestView.as_view(),
        name='payment_request'),
    url(r'^rc/(?P<uid>[0-9a-zA-Z]{6,32})/?$',
        views_v1.ReceiptView.as_view(),
        name='receipt'),
    url(r'^prc/(?P<uid>[0-9a-zA-Z]{6})/?$',
        views_v2.DepositViewSet.as_view(
            actions={'get': 'receipt'},
            renderer_classes=[renderers.PDFRenderer]),
        name='deposit-receipt'),
    url(r'^wrc/(?P<uid>[0-9a-zA-Z]{6})/?$',
        views_v2.WithdrawalViewSet.as_view(
            actions={'get': 'receipt'},
            renderer_classes=[renderers.PDFRenderer]),
        name='withdrawal-receipt'),
]

api_v2_router = routers.DefaultRouter()
api_v2_router.register('payments',
                       views_v2.DepositViewSet,
                       base_name='deposit')
api_v2_router.register('withdrawals',
                       views_v2.WithdrawalViewSet,
                       base_name='withdrawal')
api_v2_router.register('batches',
                       views_v2.DeviceBatchViewSet,
                       base_name='batch')
api_v2_router.register('devices',
                       views_v2.DeviceViewSet,
                       base_name='device')

api_v2_urls = [
    url(r'^', include(api_v2_router.urls)),
    url(r'^ping/', views_v2.PingView.as_view(), name='ping'),
]

urlpatterns = [
    url(r'^api/', include(api_v1_urls)),
    url(r'', include(short_urls, namespace='short')),
    url(r'^api/v2/', include(api_v2_urls, namespace='v2')),
]

xbterminal/website/urls.py
from django.conf.urls import url

from website import views

urlpatterns = [
    url(r'^$', views.LandingView.as_view(), name='landing'),
    url(r'^android-app$', views.android_app, name='android_app'),
    url(r'^ios-app$', views.ios_app, name='ios_app'),
    url(r'^privacy/$', views.PrivacyPolicyView.as_view(), name='privacy'),
    url(r'^terms/$', views.TermsConditionsView.as_view(), name='terms'),
    url(r'^team/$', views.TeamView.as_view(), name='team'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact'),
    url(r'^feedback/$', views.FeedbackView.as_view(), name='feedback'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^reset_password/$', views.ResetPasswordView.as_view(), name='reset_password'),
    url(r'^register/$', views.RegistrationView.as_view(), name='registration'),
    url(r'^activate/$',
        views.ActivationWizard.as_view(),
        name='activation_wizard'),
    url(r'^activate/(?P<merchant_code>\w{6})/$',
        views.ActivateDeviceView.as_view(),
        name='activate_device_nologin'),
    url(r'^activate/(?P<merchant_code>\w{6})/(?P<device_key>[0-9a-zA-Z]{8,64})/$',
        views.DeviceActivationView.as_view(),
        name='device_activation_nologin'),

    url(r'^profile/$', views.UpdateProfileView.as_view(), name='profile'),
    url(r'^change_password/$', views.ChangePasswordView.as_view(), name='change_password'),
    url(r'^verification/$', views.VerificationView.as_view(), name='verification'),
    url(r'^verification/(?P<merchant_pk>\d+)/(?P<name>.+)$',
        views.VerificationFileView.as_view(),
        name='verification_file'),

    url(r'^accounts/$',
        views.AccountListView.as_view(),
        name='accounts'),
    url(r'^accounts/(?P<currency_code>\w{3,5})/$',
        views.EditAccountView.as_view(),
        name='account'),
    url(r'^accounts/(?P<currency_code>\w{3,5})/add_funds/$',
        views.AddFundsView.as_view(),
        name='account_add_funds'),
    url(r'^accounts/(?P<currency_code>\w{3,5})/withdraw/$',
        views.WithdrawToBankAccountView.as_view(),
        name='account_withdrawal'),
    url(r'^accounts/(?P<currency_code>\w{3,5})/transactions/$',
        views.AccountTransactionListView.as_view(),
        name='account_transactions'),
    url(r'^accounts/(?P<currency_code>\w{3,5})/report/$',
        views.AccountReportView.as_view(),
        name='account_report'),

    url(r'^devices/$',
        views.DeviceListView.as_view(),
        name='devices'),
    url(r'^devices/activate/$',
        views.ActivateDeviceView.as_view(),
        name='activate_device'),
    url(r'^devices/(?P<device_key>[0-9a-zA-Z]{8,64})/$',
        views.UpdateDeviceView.as_view(),
        name='device'),
    url(r'^devices/(?P<device_key>[0-9a-zA-Z]{8,64})/status/$',
        views.DeviceStatusView.as_view(),
        name='device_status'),
    url(r'^devices/(?P<device_key>[0-9a-zA-Z]{8,64})/activation/$',
        views.DeviceActivationView.as_view(),
        name='device_activation'),
    url(r'^devices/(?P<device_key>[0-9a-zA-Z]{8,64})/transactions/$',
        views.DeviceTransactionListView.as_view(),
        name='device_transactions'),
    url(r'^devices/(?P<device_key>[0-9a-zA-Z]{8,64})/report/$',
        views.DeviceReportView.as_view(),
        name='device_report'),

    url(r'^merchants/$',
        views.MerchantListView.as_view(),
        name='merchant_list'),
    url(r'^merchants/(?P<pk>\d+)/$',
        views.MerchantInfoView.as_view(),
        name='merchant_info'),
    url(r'^merchants/(?P<pk>\d+)/devices/$',
        views.MerchantDeviceListView.as_view(),
        name='merchant_device_list'),
    url(r'^merchants/(?P<pk>\d+)/devices/(?P<device_key>[0-9a-zA-Z]{8,64})/$',
        views.MerchantDeviceInfoView.as_view(),
        name='merchant_device_info'),
]

xbterminal/xbterminal/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.i18n import javascript_catalog

from oauth2_provider.views import TokenView

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^oauth/token/', TokenView.as_view(), name='token'),
    url(r'^jsi18n/$',
        javascript_catalog,
        {'packages': ('xbterminal',)},
        name='javascript-catalog'),
    url(r'', include('api.urls', namespace='api')),
]

urlpatterns += i18n_patterns(
    url(r'', include('website.urls', namespace='website')),
)

xbterminal/website/models.py
import datetime
from decimal import Decimal
import os
import uuid

from django.apps import apps
from django.conf import settings
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin)
from django.contrib.postgres.fields import JSONField
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models.signals import pre_save, post_delete
from django.dispatch import receiver
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from constance import config
from django_countries.fields import CountryField
from django_fsm import FSMField, transition
from extended_choices import Choices
from localflavor.generic.models import BICField, IBANField

from website.validators import (
    validate_phone,
    validate_post_code,
    validate_name,
    validate_coin_address,
    validate_public_key)
from website.utils.files import (
    get_verification_file_name,
    verification_file_path_gen)
from common.uids import generate_alphanumeric_code, generate_b58_uid
from transactions.constants import COIN_DEC_PLACES
from transactions.utils.compat import (
    get_bitcoin_network,
    get_account_balance,
    get_account_transactions,
    get_device_transactions)


class UserManager(BaseUserManager):

    def _create_user(self, email, password, is_staff, is_superuser, commit):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        user = self.model(email=self.normalize_email(email),
                          is_staff=is_staff,
                          is_superuser=is_superuser)
        user.set_password(password)
        if commit:
            user.save(using=self._db)
        return user

    def create_user(self, email, password=None, commit=True):
        return self._create_user(email, password, False, False, commit)

    def create_superuser(self, email, password):
        return self._create_user(email, password, True, True, True)


class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(max_length=254, unique=True)

    is_staff = models.BooleanField(
        'staff status',
        default=False,
        help_text='Designates whether the user can log into this admin site.')
    is_active = models.BooleanField(
        'active',
        default=True,
        help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.')

    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    @property
    def role(self):
        if self.is_staff:
            return 'administrator'
        elif hasattr(self, 'merchant'):
            return 'merchant'
        elif self.groups.filter(name='controllers').exists():
            return 'controller'


class Language(models.Model):
    name = models.CharField(max_length=50, unique=True)
    code = models.CharField(max_length=2, unique=True)
    fractional_split = models.CharField(max_length=1, default=".")
    thousands_split = models.CharField(max_length=1, default=",")

    def __unicode__(self):
        return self.name


def get_language(country_code):
    if country_code == 'FR':
        language_code = 'fr'
    elif country_code in ['DE', 'AT', 'CH']:
        language_code = 'de'
    elif country_code in ['RU', 'UA', 'BY', 'KZ']:
        language_code = 'ru'
    else:
        language_code = 'en'
    return Language.objects.get(code=language_code)


class Currency(models.Model):
    name = models.CharField(max_length=50, unique=True)
    postfix = models.CharField(max_length=50, default="")
    prefix = models.CharField(max_length=50, default="")
    is_fiat = models.BooleanField()
    amount_1 = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=Decimal('1.00'),
        help_text=_('Default value for payment amount button 1.'))
    amount_2 = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=Decimal('2.50'),
        help_text=_('Default value for payment amount button 2.'))
    amount_3 = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=Decimal('10.00'),
        help_text=_('Default value for payment amount button 3.'))
    amount_shift = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=Decimal('0.05'),
        help_text=_('Default value for payment amount shift button.'))
    max_payout = models.DecimalField(
        _('Maximum payout'),
        max_digits=20,
        decimal_places=8,
        default=0)
    is_enabled = models.BooleanField()

    class Meta:
        ordering = ('is_fiat', 'id')
        verbose_name_plural = 'currencies'

    def __unicode__(self):
        return self.name


def get_currency(country_code):
    if country_code == 'GB':
        currency_code = 'GBP'
    elif country_code in ['AT', 'BE', 'DE', 'GR', 'IE', 'ES',
                          'IT', 'CY', 'LV', 'LU', 'MT', 'NL',
                          'PT', 'SK', 'SI', 'FI', 'FR', 'EE']:
        # Eurozone
        currency_code = 'EUR'
    else:
        currency_code = 'USD'
    return Currency.objects.get(name=currency_code)


class UITheme(models.Model):

    name = models.CharField(max_length=50, unique=True)

    def __unicode__(self):
        return self.name


# TODO: remove choices
INSTANTFIAT_PROVIDERS = Choices(
    ('CRYPTOPAY', 1, 'CryptoPay'),
    ('GOCOIN', 2, 'GoCoin'),
)

KYC_DOCUMENT_TYPES = Choices(
    ('ID_FRONT', 1, 'ID document - frontside'),
    ('ADDRESS', 2, 'Address document'),
    ('ID_BACK', 3, 'ID document - backside'),
)


class MerchantAccount(models.Model):

    VERIFICATION_STATUSES = [
        ('unverified', _('unverified')),
        ('pending', _('verification pending')),
        ('verified', _('verified')),
    ]

    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name="merchant")
    company_name = models.CharField(_('Company name'), max_length=255, unique=True)
    trading_name = models.CharField(_('Trading name'), max_length=255, blank=True)

    business_address = models.CharField(_('Business address'), max_length=255, null=True)
    business_address1 = models.CharField('', max_length=255, blank=True, default='')
    business_address2 = models.CharField('', max_length=255, blank=True, default='')
    town = models.CharField(_('Town'), max_length=64, null=True)
    county = models.CharField(_('State / County'), max_length=128, blank=True, default='')
    post_code = models.CharField(_('Post code'), max_length=32, validators=[validate_post_code], null=True)
    country = CountryField(_('Country'), default='GB')

    contact_first_name = models.CharField(
        _('Contact first name'),
        max_length=255,
        validators=[validate_name])
    contact_last_name = models.CharField(
        _('Contact last name'),
        max_length=255,
        validators=[validate_name])
    contact_phone = models.CharField(_('Contact phone'), max_length=32, validators=[validate_phone], null=True)
    contact_email = models.EmailField(_('Contact email'), max_length=254, unique=True)

    # Display language
    language = models.ForeignKey(Language, default=1)  # by default, English, see fixtures
    # Display currency
    currency = models.ForeignKey(Currency, default=1)  # by default, GBP, see fixtures
    ui_theme = models.ForeignKey(UITheme, default=1)  # 'default' theme, see fixtures

    # TODO: remove fields
    instantfiat_provider = models.PositiveSmallIntegerField(
        _('InstantFiat provider'),
        choices=INSTANTFIAT_PROVIDERS,
        blank=True,
        null=True)
    instantfiat_merchant_id = models.CharField(
        _('InstantFiat merchant ID'),
        max_length=50,
        blank=True,
        null=True)
    instantfiat_email = models.EmailField(
        _('InstantFiat merchant email'),
        blank=True,
        null=True)
    instantfiat_api_key = models.CharField(
        _('InstantFiat API key'),
        max_length=200,
        blank=True,
        null=True)
    tx_confidence_threshold = models.FloatField(
        _('TX confidence threshold'),
        blank=True,
        null=True,
        validators=[
            MinValueValidator(0),
            MaxValueValidator(1),
        ])

    verification_status = models.CharField(_('KYC'), max_length=50, choices=VERIFICATION_STATUSES, default='unverified')

    activation_code = models.CharField(
        max_length=6,
        editable=False,
        unique=True)
    comments = models.TextField(blank=True)

    def __unicode__(self):
        if self.trading_name:
            return u'{0} ({1})'.format(self.company_name, self.trading_name)
        else:
            return self.company_name

    @property
    def billing_address(self):
        strings = [
            self.business_address,
            self.business_address1,
            self.town,
            self.county,
            self.post_code,
            self.country.name,
        ]
        return [s for s in strings if s]

    @property
    def contact_name(self):
        return self.contact_first_name + ' ' + self.contact_last_name

    @property
    def is_profile_complete(self):
        return (bool(self.business_address) and
                bool(self.town) and
                bool(self.post_code) and
                bool(self.contact_phone))

    def get_kyc_document(self, document_type, status):
        """
        Get latest KYC document for given status
        """
        try:
            return self.kycdocument_set.\
                filter(document_type=document_type, status=status).\

xbterminal/website/templates/cabinet/merchant/account_list.html
{% extends "cabinet/base.html" %}
{% load i18n website_tags %}

{% block cabinet_content %}
<table id="accounts" class="table table-striped table-bordered table-responsive">
    <tr>
        <th>{% trans 'Currency' %}</th>
        <th>{% trans 'Balance' %}</th>
        <th>{% trans 'Balance min.' %}</th>
        <th>{% trans 'Balance max.' %}</th>
        <th>{% trans 'Actions' %}</th>
    </tr>
    {% for account in accounts %}
    <tr>
        <td><a href="{% url 'website:account' currency_code=account.currency.name|lower %}">
            {{ account.currency.name }}
        </a></td>
        <td {% if account.balance < account.balance_min %}class="balance-too-low"{% endif %}>
            {{ account.balance|amount:account.currency.name }}
        </td>
        <td>{{ account.balance_min|amount:account.currency.name }}</td>
        <td>{{ account.balance_max|amount:account.currency.name }}</td>
        <td>
            {% if account.currency.is_enabled and not account.currency.is_fiat %}
            <a href="{% url 'website:account_add_funds' currency_code=account.currency.name|lower %}" target="_blank">
                Add funds
            </a>
            <br>
            {% endif %}
            {% if account.instantfiat %}
            <a href="{% url 'website:account_withdrawal' currency_code=account.currency.name|lower %}">
                Withdraw
            </a>
            <br>
            {% endif %}
            <a href="{% url 'website:account_transactions' currency_code=account.currency.name|lower %}">
                View transactions
            </a>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

xbterminal/website/templates/cabinet/merchant/activation.html
{% extends 'cabinet/base.html' %}
{% load bootstrap3 i18n staticfiles %}

{% block js %}
{% if device %}
<script src="{% static 'js/activation.js' %}"></script>
<script>
    var checkUrl = '{% url 'api:v2:device-detail' device.key %}';
</script>
{% endif %}
{% endblock %}

{% block cabinet_content %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h3>{% trans 'Module activation' %}</h3>
        {% if not user.is_authenticated %}
        <h4>{{ merchant }}</h4>
        {% endif %}
        {% if form %}
        <form id="activation-form" action="" method="post" autocomplete="off">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-default">
                {% trans 'Activate' %}
            </button>
            {% if user.is_authenticated %}
            <a href="{% url 'website:devices' %}" class="btn btn-default">
                {% trans 'Cancel' %}
            </a>
            <p>&nbsp;</p>
            <div class="form-group">
                <label class="control-label" for="id_activation_url">
                    {% trans 'To activate module without login use following link' %}
                </label>
                <input class="form-control" id="id_activation_url" type="text" value="{{ activation_url }}" readonly>
            </div>
            {% endif %}
        </form>
        {% else %}
            <p class="large activation-in-progress">
                {% trans 'Activation in progress. Do not turn off the module.' %}<br>
                <img src="{% static 'img/loading.gif' %}">
            </p>
            <p class="large activation-error">
                {% trans 'Activation failed. Please contact support.' %}
            </p>
            <p class="large activation-success">
                {% trans 'Activation successful.' %}
                {% if user.is_authenticated %}
                <a href="{% url 'website:device' device.key %}">
                    {% trans 'Show device settings.' %}
                </a>
                {% endif %}
            </p>
        {% endif %}
    </div>
</div>
{% endblock %}

xbterminal/website/templates/cabinet/merchant/device_list.html
{% extends "cabinet/base.html" %}
{% load i18n %}

{% block cabinet_content %}
<div>
    <a class="btn btn-default" href="{% url 'website:activate_device' %}">{% trans 'Activate payment module' %}</a>
</div>
<table id="devices" class="table table-striped table-bordered table-responsive">
    <tr>
        <th>{% trans 'Name' %}</th>
        <th>{% trans 'Status' %}</th>
        <th>{% trans 'Account' %}</th>
        <th>{% trans 'Actions' %}</th>
    </tr>
    {% for device in devices %}
    <tr>
        <td>
            {% if device.status == 'activation_in_progress' or device.status == 'activation_error' %}
            <a href="{% url 'website:device_activation' device.key %}">{{ device.name }}</a>
            {% else %}
            <a href="{% url 'website:device' device.key %}">{{ device.name }}</a>
            {% endif %}
        </td>
        <td>
            {{ device.get_status_display }}
            {% if device.is_online %}<div class="device-online" title="device online">•</div>{% endif %}
        </td>
        <td>{{ device.account }}</td>
        <td>
            {% if device.status == 'active' or device.status == 'suspended' %}
            <div><a href="{% url 'website:device_transactions' device.key %}">
                {% trans 'view transactions' %}
            </a></div>
            <div><a href="{% url 'website:device_status' device.key %}">
                {% if device.status == 'active' %}{% trans 'suspend module' %}
                {% elif device.status == 'suspended' %}{% trans 'reenable module' %}
                {% endif %}
            </a></div>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

xbterminal/website/templates/cabinet/merchant/profile_form.html
{% extends "cabinet/base.html" %}
{% load bootstrap3 i18n %}

{% block cabinet_content %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="clearfix">
            <h3 class="pull-left">{% trans 'Merchant profile' %}</h3>
            {% if user.merchant.verification_status == 'verified' %}
            <h3 id="profile-verification-status" class="pull-right">
                <small><a href="{% url 'website:verification' %}">{{ user.merchant.get_verification_status_display }}</small></a>
            </h3>
            {% endif %}
        </div>
        <a class="change-password" href="{% url 'website:change_password' %}">Change password</a>
        <form id="profile-form" action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">{% bootstrap_field form.contact_first_name %}</div>
                <div class="col-md-6">{% bootstrap_field form.contact_last_name %}</div>
            </div>
            <div class="row">
                <div class="col-md-6">{% bootstrap_field form.contact_email %}</div>
                <div class="col-md-6">{% bootstrap_field form.contact_phone %}</div>
            </div>
            <div class="row">
                <div class="col-md-6">{% bootstrap_field form.company_name %}</div>
                <div class="col-md-6">{% bootstrap_field form.trading_name %}</div>
            </div>
            {% bootstrap_field form.business_address %}
            {% bootstrap_field form.business_address1 %}
            <div class="row">
                <div class="col-md-6">{% bootstrap_field form.town %}</div>
                <div class="col-md-6">{% bootstrap_field form.post_code %}</div>
            </div>
            <div class="row">
                <div class="col-md-6">{% bootstrap_field form.county %}</div>
                <div class="col-md-6">{% bootstrap_field form.country %}</div>
            </div>
            <div class="row">
                <div class="col-md-6"><button type="submit" class="btn btn-default pull-right">{% trans 'Update' %}</button></div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

xbterminal/website/templates/cabinet/merchant/verification.html
{% extends "cabinet/base.html" %}
{% load bootstrap3 staticfiles i18n %}

{% block js %}
<script src="{% static 'lib/jquery.ui.widget.js' %}"></script>
<script src="{% static 'lib/jquery.iframe-transport.js' %}"></script>
<script src="{% static 'lib/jquery.fileupload.js' %}"></script>
<script src="{% static 'js/verification.js' %}"></script>
{% endblock %}

{% block cabinet_content %}
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h3>{% trans 'Account verification' %}</h3>
        {% if user.merchant.verification_status == 'unverified' %}
            {% blocktrans %}
            <p>Your merchant account must be verified to receive fiat payouts. To verify your merchant account, you must submit a government issued ID from the company principal, as well as a corporate document showing the registered identity of the business in the jurisdiction where the company operates. If you're a sole trader and not incorporated - then a proof of residence is needed instead of a corporate document.</p>
            <ol>
                <li>Identity Document (principal)
                    <ul>
                        <li>International passport</li>
                        <li>National ID card (both sides)</li>
                        <li>Driver's license</li>
                    </ul>
                </li>
                <li>Corporate or Address Document
                    <ul>
                        <li>corporate:
                            <ul>
                                <li>articles of incorporation</li>
                                <li>membership agreement</li>
                                <li>business tax return</li>
                            </ul>
                        </li>
                        <li>address:
                            <ul>
                                <li>bank statement</li>
                                <li>utility bill (except mobile phone bills)</li>
                                <li>council tax bill</li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ol>
            <p>DOCUMENT GUIDELINES:</p>
            <p>Documents need to be visible in their entirety. Please do not crop just the address.<br>
                Scans should be of high quality. All text must be legible.<br>
                Identification documents must be current, expired IDs will not be accepted.<br>
                Corporate documents must be a scanned image of an original paper document.<br>
                Address document must be no more than three months old.</p>
            {% endblocktrans %}
            {% for form in forms %}
                <form class="upload-form" action="{% url 'website:verification_file' merchant_pk=user.merchant.pk name=form.document_type %}" method="POST">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                </form>
            {% endfor %}
            <form id="verification-form" action="{% url 'website:verification' %}" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6"><button type="submit" class="btn btn-default pull-right">{% trans 'Submit' %}</button></div>
                    <div class="col-md-6">
                        <a href="{% url 'website:profile' %}" class="btn pull-left">{% trans 'Cancel' %}</a>
                        <img id="loading-image" src="{% static 'img/loading.gif' %}">
                    </div>
                </div>
            </form>
        {% else %}
            {% if user.merchant.verification_status == 'pending' %}
            <p class="large">{% trans 'Verification pending' %}</p>
            <p>
                {% blocktrans %}
                You have successfully uploaded your documents for verification, now it will be processed by our team. You will receive an email notification once your account will be confirmed. We will contact you should we have any questions about the documents uploaded or other related matters. Uploaded documents are:
                {% endblocktrans %}
            </p>
            {% elif user.merchant.verification_status == 'verified' %}
            <p class="large">{% trans 'Verified' %}</p>
            <p>
                {% blocktrans %}
                Your account has been verified, you can now execute withdrawals to your bank accounts.<br>
                You have previously uploaded these documents:
                {% endblocktrans %}
            </p>
            {% endif %}
            <div>
                {% for document in documents %}
                <a href="{% url 'website:verification_file' merchant_pk=user.merchant.pk name=document.base_name %}">{{ document.original_name }}</a><br>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}