xbterminal/api/urls.py
from django.conf.urls import include, url
from rest_framework import routers

from api import views_v1, views_v2, renderers


api_v1_urls = [
    url(r'^merchant/?$',
        views_v1.MerchantView.as_view(),
        name='merchant'),
    url(r'^devices/?$',
        views_v1.DevicesView.as_view(),
        name='devices'),
    url(r'^devices/(?P<key>[0-9a-zA-Z]{8,32})/?$',
        views_v1.device,
        name='device'),

    url(r'^payments/init/?$',
        views_v1.PaymentInitView.as_view(),
        name='payment_init'),
    url(r'^payments/(?P<uid>[0-9a-zA-Z]{6,32})/request/?$',
        views_v1.PaymentRequestView.as_view(),
        name='payment_request'),
    url(r'^payments/(?P<uid>[0-9a-zA-Z]{6,32})/response/?$',
        views_v1.PaymentResponseView.as_view(),
        name='payment_response'),
    url(r'^payments/(?P<uid>[0-9a-zA-Z]{6,32})/check/?$',
        views_v1.PaymentCheckView.as_view(),
        name='payment_check'),

    url(r'^receipts/(?P<uid>[0-9a-zA-Z]{6,32})/?$',
        views_v1.ReceiptView.as_view(),
        name='receipt'),
]

short_urls = [
    url(r'^pr/(?P<uid>[0-9a-zA-Z]{6,32})/?$',
        views_v1.PaymentRequestView.as_view(),
        name='payment_request'),
    url(r'^rc/(?P<uid>[0-9a-zA-Z]{6,32})/?$',
        views_v1.ReceiptView.as_view(),
        name='receipt'),
    url(r'^prc/(?P<uid>[0-9a-zA-Z]{6})/?$',
        views_v2.DepositViewSet.as_view(
            actions={'get': 'receipt'},
            renderer_classes=[renderers.PDFRenderer]),
        name='deposit-receipt'),
    url(r'^wrc/(?P<uid>[0-9a-zA-Z]{6})/?$',
        views_v2.WithdrawalViewSet.as_view(
            actions={'get': 'receipt'},
            renderer_classes=[renderers.PDFRenderer]),
        name='withdrawal-receipt'),
]

api_v2_router = routers.DefaultRouter()
api_v2_router.register('payments',
                       views_v2.DepositViewSet,
                       base_name='deposit')
api_v2_router.register('withdrawals',
                       views_v2.WithdrawalViewSet,
                       base_name='withdrawal')
api_v2_router.register('batches',
                       views_v2.DeviceBatchViewSet,
                       base_name='batch')
api_v2_router.register('devices',
                       views_v2.DeviceViewSet,
                       base_name='device')

api_v2_urls = [
    url(r'^', include(api_v2_router.urls)),
    url(r'^ping/', views_v2.PingView.as_view(), name='ping'),
]

urlpatterns = [
    url(r'^api/', include(api_v1_urls)),
    url(r'', include(short_urls, namespace='short')),
    url(r'^api/v2/', include(api_v2_urls, namespace='v2')),
]

xbterminal/website/urls.py
from django.conf.urls import url

from website import views

urlpatterns = [
    url(r'^$', views.LandingView.as_view(), name='landing'),
    url(r'^android-app$', views.android_app, name='android_app'),
    url(r'^ios-app$', views.ios_app, name='ios_app'),
    url(r'^privacy/$', views.PrivacyPolicyView.as_view(), name='privacy'),
    url(r'^terms/$', views.TermsConditionsView.as_view(), name='terms'),
    url(r'^team/$', views.TeamView.as_view(), name='team'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact'),
    url(r'^feedback/$', views.FeedbackView.as_view(), name='feedback'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^reset_password/$', views.ResetPasswordView.as_view(), name='reset_password'),
    url(r'^register/$', views.RegistrationView.as_view(), name='registration'),
    url(r'^activate/$',
        views.ActivationWizard.as_view(),
        name='activation_wizard'),
    url(r'^activate/(?P<merchant_code>\w{6})/$',
        views.ActivateDeviceView.as_view(),
        name='activate_device_nologin'),
    url(r'^activate/(?P<merchant_code>\w{6})/(?P<device_key>[0-9a-zA-Z]{8,64})/$',
        views.DeviceActivationView.as_view(),
        name='device_activation_nologin'),

    url(r'^profile/$', views.UpdateProfileView.as_view(), name='profile'),
    url(r'^change_password/$', views.ChangePasswordView.as_view(), name='change_password'),
    url(r'^verification/$', views.VerificationView.as_view(), name='verification'),
    url(r'^verification/(?P<merchant_pk>\d+)/(?P<name>.+)$',
        views.VerificationFileView.as_view(),
        name='verification_file'),

    url(r'^accounts/$',
        views.AccountListView.as_view(),
        name='accounts'),
    url(r'^accounts/(?P<currency_code>\w{3,5})/$',
        views.EditAccountView.as_view(),
        name='account'),
    url(r'^accounts/(?P<currency_code>\w{3,5})/add_funds/$',
        views.AddFundsView.as_view(),
        name='account_add_funds'),
    url(r'^accounts/(?P<currency_code>\w{3,5})/withdraw/$',
        views.WithdrawToBankAccountView.as_view(),
        name='account_withdrawal'),
    url(r'^accounts/(?P<currency_code>\w{3,5})/transactions/$',
        views.AccountTransactionListView.as_view(),
        name='account_transactions'),
    url(r'^accounts/(?P<currency_code>\w{3,5})/report/$',
        views.AccountReportView.as_view(),
        name='account_report'),

    url(r'^devices/$',
        views.DeviceListView.as_view(),
        name='devices'),
    url(r'^devices/activate/$',
        views.ActivateDeviceView.as_view(),
        name='activate_device'),
    url(r'^devices/(?P<device_key>[0-9a-zA-Z]{8,64})/$',
        views.UpdateDeviceView.as_view(),
        name='device'),
    url(r'^devices/(?P<device_key>[0-9a-zA-Z]{8,64})/status/$',
        views.DeviceStatusView.as_view(),
        name='device_status'),
    url(r'^devices/(?P<device_key>[0-9a-zA-Z]{8,64})/activation/$',
        views.DeviceActivationView.as_view(),
        name='device_activation'),
    url(r'^devices/(?P<device_key>[0-9a-zA-Z]{8,64})/transactions/$',
        views.DeviceTransactionListView.as_view(),
        name='device_transactions'),
    url(r'^devices/(?P<device_key>[0-9a-zA-Z]{8,64})/report/$',
        views.DeviceReportView.as_view(),
        name='device_report'),

    url(r'^merchants/$',
        views.MerchantListView.as_view(),
        name='merchant_list'),
    url(r'^merchants/(?P<pk>\d+)/$',
        views.MerchantInfoView.as_view(),
        name='merchant_info'),
    url(r'^merchants/(?P<pk>\d+)/devices/$',
        views.MerchantDeviceListView.as_view(),
        name='merchant_device_list'),
    url(r'^merchants/(?P<pk>\d+)/devices/(?P<device_key>[0-9a-zA-Z]{8,64})/$',
        views.MerchantDeviceInfoView.as_view(),
        name='merchant_device_info'),
]

xbterminal/xbterminal/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.i18n import javascript_catalog

from oauth2_provider.views import TokenView

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^oauth/token/', TokenView.as_view(), name='token'),
    url(r'^jsi18n/$',
        javascript_catalog,
        {'packages': ('xbterminal',)},
        name='javascript-catalog'),
    url(r'', include('api.urls', namespace='api')),
]

urlpatterns += i18n_patterns(
    url(r'', include('website.urls', namespace='website')),
)

xbterminal/website/views.py
from decimal import Decimal
import json
import datetime
import re

from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponse, Http404, StreamingHttpResponse
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.views.generic import View
from django.views.generic.base import ContextMixin, TemplateResponseMixin
from django.utils.decorators import method_decorator
from django.core.urlresolvers import resolve, reverse
from django.db.transaction import atomic
from django.utils.translation import ugettext as _

from formtools.wizard.views import CookieWizardView
from ipware.ip import get_real_ip

from api.utils import activation
from api.utils.urls import construct_absolute_url

from website import forms, models
from website.utils import email, kyc, reports


class LandingView(TemplateResponseMixin, View):
    """
    Landing page
    """
    template_name = "website/landing.html"

    def get(self, *args, **kwargs):
        return self.render_to_response({})


def android_app(request):
    return redirect('https://play.google.com/store/apps/details?id=ua.xbterminal.bitcoin')


def ios_app(request):
    return redirect('https://itunes.apple.com/us/app/xbterminal-bitcoin-pos/id909352652')


class ContactView(TemplateResponseMixin, View):
    """
    Contact form
    """
    template_name = "website/contact.html"

    def get(self, *args, **kwargs):
        form = forms.ContactForm(user_ip=get_real_ip(self.request))
        return self.render_to_response({'form': form})

    def post(self, *args, **kwargs):
        form = forms.ContactForm(self.request.POST,
                                 user_ip=get_real_ip(self.request))
        if form.is_valid():
            email.send_contact_email(form.cleaned_data)
            return self.render_to_response({})
        else:
            return self.render_to_response({'form': form})


class FeedbackView(TemplateResponseMixin, View):
    """
    Feedback form
    """
    template_name = "website/feedback.html"

    def get(self, *args, **kwargs):
        form = forms.FeedbackForm(user_ip=get_real_ip(self.request))
        return self.render_to_response({'form': form})

    def post(self, *args, **kwargs):
        form = forms.FeedbackForm(self.request.POST,
                                  user_ip=get_real_ip(self.request))
        if form.is_valid():
            email.send_feedback_email(form.cleaned_data)
            return self.render_to_response({})
        else:
            return self.render_to_response({'form': form})


class PrivacyPolicyView(TemplateResponseMixin, View):
    """
    Privacy policy page
    """
    template_name = "website/privacy.html"

    def get(self, *args, **kwargs):
        return self.render_to_response({})


class TermsConditionsView(TemplateResponseMixin, View):
    """
    Terms & Conditions page
    """
    template_name = "website/tc.html"

    def get(self, *args, **kwargs):
        return self.render_to_response({})


class TeamView(TemplateResponseMixin, View):
    """
    Team page
    """
    template_name = "website/team.html"

    def get(self, *args, **kwargs):
        return self.render_to_response({})


class LoginView(ContextMixin, TemplateResponseMixin, View):
    """
    Login page
    """
    template_name = "website/login.html"

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        context['next'] = self.request.POST.get(
            'next', self.request.GET.get('next', ''))
        return context

    def _redirect_after_login(self, user):
        if user.role == 'administrator':
            url = reverse('admin:index')
        elif user.role == 'merchant':
            url = reverse('website:devices')
        elif user.role == 'controller':
            url = reverse('website:merchant_list')
        else:
            url = reverse('website:landing')
        return redirect(url)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated():
            return self._redirect_after_login(self.request.user)
        context = self.get_context_data(**kwargs)
        context['form'] = forms.AuthenticationForm
        return self.render_to_response(context)

    def post(self, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        form = forms.AuthenticationForm(self.request, data=self.request.POST)
        if form.is_valid():
            user = form.get_user()
            login(self.request, user)
            return self._redirect_after_login(user)
        context['form'] = form
        return self.render_to_response(context)


class LogoutView(View):
    """
    Logout
    """
    def get(self, *args, **kwargs):
        logout(self.request)
        return redirect(reverse('website:landing'))


class ResetPasswordView(TemplateResponseMixin, View):
    """
    Reset password page
    """
    template_name = "website/reset_password.html"

    def get(self, *args, **kwargs):
        form = forms.ResetPasswordForm()
        return self.render_to_response({'form': form})

    def post(self, *args, **kwargs):
        form = forms.ResetPasswordForm(self.request.POST)
        if form.is_valid():
            form.set_new_password()
            return self.render_to_response({})
        else:
            return self.render_to_response({'form': form})


class RegistrationView(TemplateResponseMixin, View):
    """
    Registration page
    """
    template_name = "website/registration.html"

    def get(self, *args, **kwargs):
        if hasattr(self.request.user, 'merchant'):
            return redirect(reverse('website:devices'))
        form = forms.MerchantRegistrationForm()
        return self.render_to_response({'form': form})

    def post(self, *args, **kwags):
        form = forms.MerchantRegistrationForm(self.request.POST)
        if not form.is_valid():
            return self.render_to_response({'form': form})
        merchant = form.save()
        email.send_registration_info(merchant)
        login(self.request, merchant.user)
        return redirect(reverse('website:devices'))


class ActivationWizard(CookieWizardView):
    """
    Activate device and login
    """
    template_name = 'website/activation.html'
    form_list = [
        forms.DeviceActivationForm,
        forms.LoginMethodForm,
        forms.AuthenticationForm,
        forms.MerchantRegistrationForm,
    ]

    def show_login_form_condition(self):
        data = self.get_cleaned_data_for_step('1') or {}
        return data.get('method') == 'login'

    def show_registration_form_condition(self):
        data = self.get_cleaned_data_for_step('1') or {}
        return data.get('method') == 'register'

    condition_dict = {
        '2': show_login_form_condition,
        '3': show_registration_form_condition,
    }

    def dispatch(self, *args, **kwargs):
        if get_current_merchant(self.request):
            return redirect(reverse('website:activate_device'))
        return super(ActivationWizard, self).dispatch(*args, **kwargs)

    @atomic
    def done(self, form_list, **kwargs):
        # Get device
        device = form_list[0].device
        # Get merchant
        if self.show_login_form_condition():
            merchant = form_list[2].get_user().merchant
        elif self.show_registration_form_condition():
            merchant = form_list[2].save()
            email.send_registration_info(merchant)
        # Start activation
        activation.start(device, merchant)
        # Login & redirect
        login(self.request, merchant.user)
        return redirect(reverse('website:device_activation',
                                kwargs={'device_key': device.key}))


def get_current_merchant(request):
    if not hasattr(request.user, 'merchant'):
        return None
    return request.user.merchant


class MerchantCabinetView(ContextMixin, View):
    """
    Base class for merchant cabinet views
    """

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.merchant = get_current_merchant(request)
        if not self.merchant:
            raise Http404
        return super(MerchantCabinetView,
                     self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(MerchantCabinetView,
                        self).get_context_data(**kwargs)
        context['cabinet_page'] = resolve(self.request.path_info).url_name
        context['merchant'] = self.merchant
        return context


class DeviceListView(TemplateResponseMixin, MerchantCabinetView):
    """
    Device list page
    """
    template_name = 'cabinet/merchant/device_list.html'

    def get(self, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['devices'] = self.merchant.device_set.order_by('-id')
        return self.render_to_response(context)


class ActivationView(MerchantCabinetView):

    def dispatch(self, request, *args, **kwargs):
        self.merchant = get_current_merchant(request)
        if not self.merchant:
            try:
                self.merchant = models.MerchantAccount.objects.get(
                    activation_code__iexact=self.kwargs.get('merchant_code'))
            except models.MerchantAccount.DoesNotExist:
                raise Http404
        return super(MerchantCabinetView, self).dispatch(request, *args, **kwargs)


class ActivateDeviceView(TemplateResponseMixin, ActivationView):

    template_name = 'cabinet/merchant/activation.html'

    def get_context_data(self, **kwargs):
        context = super(ActivateDeviceView, self).get_context_data(**kwargs)
        context['activation_url'] = construct_absolute_url(
            'website:activate_device_nologin',
            kwargs={'merchant_code': self.merchant.activation_code})

xbterminal/website/templates/website/common/analytics.html
{% if not DEBUG %}
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-54375007-1', 'auto');
ga('send', 'pageview');
</script>
{% endif %}

xbterminal/website/templates/website/common/footer.html
{% load staticfiles i18n %}

<div class="footer-1 row">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="row">
                    <div class="col-md-4">
                        <h4>{% trans 'products' %}</h4>
                        <ul class="footer-menu">
                            <li><a href="{% url 'website:landing' %}#mobile-section">{% trans 'mobile' %}</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h4>{% trans 'company' %}</h4>
                        <ul class="footer-menu">
                            <li><a href="{% url 'website:team' %}">{% trans 'team' %}</a></li>
                            <li><a href="{% url 'website:contact' %}">{% trans 'contact us' %}</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h4>{% trans 'legal' %}</h4>
                        <ul class="footer-menu">
                            <li><a href="{% url 'website:terms' %}">{% trans 'terms & conditions' %}</a></li>
                            <li><a href="{% url 'website:privacy' %}">{% trans 'privacy policy' %}</a></li>
                        </ul>
                    </div>
                </div>
                <div class="copyright">Copyright XBTerminal Ltd 2014-2016</div>
            </div>
        </div>
    </div>
</div>
<div class="footer-2 row">
    <div class="container">
        <div class="footer-logo">
            <a href="{% url 'website:landing' %}">
                <img src="{% static 'img/xbt_logo_dark.png' %}" alt="XBTerminal">
            </a>
        </div>
    </div>
</div>

xbterminal/website/templates/website/common/header.html
{% load staticfiles i18n %}

<div class="header row">
    <div id="cookie-notice">
        {% trans 'Cookies help us to deliver our services. By using our services, you agree to our use of cookies.' %}
        <button type="button">{% trans 'Got it' %}</button>
    </div>
    <div class="container">
        <nav class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{% url 'website:landing' %}" class="navbar-brand">
                    <img src="{% static 'img/xbt_logo.png' %}" alt="XBTerminal">
                </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    {% if user.role == 'merchant' %}
                    <li><a href="{% url 'website:devices' %}" {% if cabinet_page == 'devices' %}class="active"{% endif %}>{% trans 'devices' %}</a></li><!--
                    --><li><a href="{% url 'website:accounts' %}" {% if cabinet_page == 'accounts' %}class="active"{% endif %}>{% trans 'accounts' %}</a></li><!--
                    --><li><a href="{% url 'website:profile' %}" {% if cabinet_page == 'profile' or cabinet_page == 'verification' %}class="active"{% endif %}>{% trans 'profile' %}</a></li>
                    {% elif user.role == 'controller' %}
                    <li>
                        <a href="{% url 'website:merchant_list' %}"
                                {% if cabinet_page == 'merchant_list' %}class="active"{% endif %}
                                style="font-size: 0.8em;"
                        >
                            {% trans 'monitoring' %}
                        </a>
                    </li>
                    {% else %}
                    <li><a href="{% url 'website:landing' %}#about-section">{% trans 'about' %}</a></li><!--
                    --><li><a href="{% url 'website:landing' %}#mobile-section">{% trans 'mobile' %}</a></li>
                    {% endif %}
                </ul>
                <div class="user-block">
                    {% if not user.is_authenticated %}
                    <a class="login-form-title" href="{% url 'website:login' %}">{% trans 'merchant login' %}</a>
                    <form class="login-form" action="{% url 'website:login' %}" method="POST">
                        {% csrf_token %}
                        <input type="text" name="username" placeholder="{% trans 'username' %}"><br>
                        <input type="password" name="password" placeholder="{% trans 'password' %}"><br>
                        <button type="submit" class="xbt-btn-secondary">{% trans 'login' %}</button>
                    </form>
                    <a class="xbt-btn-secondary login" href="{% url 'website:login' %}">{% trans 'login' %}</a>
                    <a class="xbt-btn-primary register" href="{% url 'website:registration' %}">{% trans 'register' %}</a>
                    {% else %}
                    <div id="user-info">
                        {% if user.role == 'merchant' %}
                        {% with user.merchant.info as info %}
                        <div>
                            <a id="merchant-info-name" href="{% url 'website:profile' %}">{{ info.name }}</a>
                            {% if info.status %}
                            <a id="merchant-info-status" href="{% url 'website:verification' %}">({{ info.status }})</a>
                            {% endif %}
                        </div>
                        <div id="merchant-info-devices">{% trans 'POS active/total:' %} {{ info.active }} / {{ info.total }}</div>
                        <div id="merchant-info-tx">{% trans 'transactions today:' %} {{ info.tx_count }} / {{ user.merchant.currency.prefix }}{{ info.tx_sum|floatformat:2 }}</div>
                        {% endwith %}
                        {% else %}
                        <div>{{ user.email }}</div>
                        {% endif %}
                    </div>
                    <a class="xbt-btn-secondary logout" href="{% url 'website:logout' %}">{% trans 'logout' %}</a>
                    {% endif %}
                </div>
            </div>
        </nav>
    </div>
    <div class="user-block-bg"></div>
</div>