xbterminal/api/urls.py
from django.conf.urls import include, url
from rest_framework import routers

from api import views_v1, views_v2, renderers


api_v1_urls = [
    url(r'^merchant/?$',
        views_v1.MerchantView.as_view(),
        name='merchant'),
    url(r'^devices/?$',
        views_v1.DevicesView.as_view(),
        name='devices'),
    url(r'^devices/(?P<key>[0-9a-zA-Z]{8,32})/?$',
        views_v1.device,
        name='device'),

    url(r'^payments/init/?$',
        views_v1.PaymentInitView.as_view(),
        name='payment_init'),
    url(r'^payments/(?P<uid>[0-9a-zA-Z]{6,32})/request/?$',
        views_v1.PaymentRequestView.as_view(),
        name='payment_request'),
    url(r'^payments/(?P<uid>[0-9a-zA-Z]{6,32})/response/?$',
        views_v1.PaymentResponseView.as_view(),
        name='payment_response'),
    url(r'^payments/(?P<uid>[0-9a-zA-Z]{6,32})/check/?$',
        views_v1.PaymentCheckView.as_view(),
        name='payment_check'),

    url(r'^receipts/(?P<uid>[0-9a-zA-Z]{6,32})/?$',
        views_v1.ReceiptView.as_view(),
        name='receipt'),
]

short_urls = [
    url(r'^pr/(?P<uid>[0-9a-zA-Z]{6,32})/?$',
        views_v1.PaymentRequestView.as_view(),
        name='payment_request'),
    url(r'^rc/(?P<uid>[0-9a-zA-Z]{6,32})/?$',
        views_v1.ReceiptView.as_view(),
        name='receipt'),
    url(r'^prc/(?P<uid>[0-9a-zA-Z]{6})/?$',
        views_v2.DepositViewSet.as_view(
            actions={'get': 'receipt'},
            renderer_classes=[renderers.PDFRenderer]),
        name='deposit-receipt'),
    url(r'^wrc/(?P<uid>[0-9a-zA-Z]{6})/?$',
        views_v2.WithdrawalViewSet.as_view(
            actions={'get': 'receipt'},
            renderer_classes=[renderers.PDFRenderer]),
        name='withdrawal-receipt'),
]

api_v2_router = routers.DefaultRouter()
api_v2_router.register('payments',
                       views_v2.DepositViewSet,
                       base_name='deposit')
api_v2_router.register('withdrawals',
                       views_v2.WithdrawalViewSet,
                       base_name='withdrawal')
api_v2_router.register('batches',
                       views_v2.DeviceBatchViewSet,
                       base_name='batch')
api_v2_router.register('devices',
                       views_v2.DeviceViewSet,
                       base_name='device')

api_v2_urls = [
    url(r'^', include(api_v2_router.urls)),
    url(r'^ping/', views_v2.PingView.as_view(), name='ping'),
]

urlpatterns = [
    url(r'^api/', include(api_v1_urls)),
    url(r'', include(short_urls, namespace='short')),
    url(r'^api/v2/', include(api_v2_urls, namespace='v2')),
]

xbterminal/website/urls.py
from django.conf.urls import url

from website import views

urlpatterns = [
    url(r'^$', views.LandingView.as_view(), name='landing'),
    url(r'^android-app$', views.android_app, name='android_app'),
    url(r'^ios-app$', views.ios_app, name='ios_app'),
    url(r'^privacy/$', views.PrivacyPolicyView.as_view(), name='privacy'),
    url(r'^terms/$', views.TermsConditionsView.as_view(), name='terms'),
    url(r'^team/$', views.TeamView.as_view(), name='team'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact'),
    url(r'^feedback/$', views.FeedbackView.as_view(), name='feedback'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^reset_password/$', views.ResetPasswordView.as_view(), name='reset_password'),
    url(r'^register/$', views.RegistrationView.as_view(), name='registration'),
    url(r'^activate/$',
        views.ActivationWizard.as_view(),
        name='activation_wizard'),
    url(r'^activate/(?P<merchant_code>\w{6})/$',
        views.ActivateDeviceView.as_view(),
        name='activate_device_nologin'),
    url(r'^activate/(?P<merchant_code>\w{6})/(?P<device_key>[0-9a-zA-Z]{8,64})/$',
        views.DeviceActivationView.as_view(),
        name='device_activation_nologin'),

    url(r'^profile/$', views.UpdateProfileView.as_view(), name='profile'),
    url(r'^change_password/$', views.ChangePasswordView.as_view(), name='change_password'),
    url(r'^verification/$', views.VerificationView.as_view(), name='verification'),
    url(r'^verification/(?P<merchant_pk>\d+)/(?P<name>.+)$',
        views.VerificationFileView.as_view(),
        name='verification_file'),

    url(r'^accounts/$',
        views.AccountListView.as_view(),
        name='accounts'),
    url(r'^accounts/(?P<currency_code>\w{3,5})/$',
        views.EditAccountView.as_view(),
        name='account'),
    url(r'^accounts/(?P<currency_code>\w{3,5})/add_funds/$',
        views.AddFundsView.as_view(),
        name='account_add_funds'),
    url(r'^accounts/(?P<currency_code>\w{3,5})/withdraw/$',
        views.WithdrawToBankAccountView.as_view(),
        name='account_withdrawal'),
    url(r'^accounts/(?P<currency_code>\w{3,5})/transactions/$',
        views.AccountTransactionListView.as_view(),
        name='account_transactions'),
    url(r'^accounts/(?P<currency_code>\w{3,5})/report/$',
        views.AccountReportView.as_view(),
        name='account_report'),

    url(r'^devices/$',
        views.DeviceListView.as_view(),
        name='devices'),
    url(r'^devices/activate/$',
        views.ActivateDeviceView.as_view(),
        name='activate_device'),
    url(r'^devices/(?P<device_key>[0-9a-zA-Z]{8,64})/$',
        views.UpdateDeviceView.as_view(),
        name='device'),
    url(r'^devices/(?P<device_key>[0-9a-zA-Z]{8,64})/status/$',
        views.DeviceStatusView.as_view(),
        name='device_status'),
    url(r'^devices/(?P<device_key>[0-9a-zA-Z]{8,64})/activation/$',
        views.DeviceActivationView.as_view(),
        name='device_activation'),
    url(r'^devices/(?P<device_key>[0-9a-zA-Z]{8,64})/transactions/$',
        views.DeviceTransactionListView.as_view(),
        name='device_transactions'),
    url(r'^devices/(?P<device_key>[0-9a-zA-Z]{8,64})/report/$',
        views.DeviceReportView.as_view(),
        name='device_report'),

    url(r'^merchants/$',
        views.MerchantListView.as_view(),
        name='merchant_list'),
    url(r'^merchants/(?P<pk>\d+)/$',
        views.MerchantInfoView.as_view(),
        name='merchant_info'),
    url(r'^merchants/(?P<pk>\d+)/devices/$',
        views.MerchantDeviceListView.as_view(),
        name='merchant_device_list'),
    url(r'^merchants/(?P<pk>\d+)/devices/(?P<device_key>[0-9a-zA-Z]{8,64})/$',
        views.MerchantDeviceInfoView.as_view(),
        name='merchant_device_info'),
]

xbterminal/xbterminal/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.i18n import javascript_catalog

from oauth2_provider.views import TokenView

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^oauth/token/', TokenView.as_view(), name='token'),
    url(r'^jsi18n/$',
        javascript_catalog,
        {'packages': ('xbterminal',)},
        name='javascript-catalog'),
    url(r'', include('api.urls', namespace='api')),
]

urlpatterns += i18n_patterns(
    url(r'', include('website.urls', namespace='website')),
)

xbterminal/website/views.py
from decimal import Decimal
import json
import datetime
import re

from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponse, Http404, StreamingHttpResponse
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.views.generic import View
from django.views.generic.base import ContextMixin, TemplateResponseMixin
from django.utils.decorators import method_decorator
from django.core.urlresolvers import resolve, reverse
from django.db.transaction import atomic
from django.utils.translation import ugettext as _

from formtools.wizard.views import CookieWizardView
from ipware.ip import get_real_ip

from api.utils import activation
from api.utils.urls import construct_absolute_url

from website import forms, models
from website.utils import email, kyc, reports


class LandingView(TemplateResponseMixin, View):
    """
    Landing page
    """
    template_name = "website/landing.html"

    def get(self, *args, **kwargs):
        return self.render_to_response({})


def android_app(request):
    return redirect('https://play.google.com/store/apps/details?id=ua.xbterminal.bitcoin')


def ios_app(request):
    return redirect('https://itunes.apple.com/us/app/xbterminal-bitcoin-pos/id909352652')


class ContactView(TemplateResponseMixin, View):
    """
    Contact form
    """
    template_name = "website/contact.html"

    def get(self, *args, **kwargs):
        form = forms.ContactForm(user_ip=get_real_ip(self.request))
        return self.render_to_response({'form': form})

    def post(self, *args, **kwargs):
        form = forms.ContactForm(self.request.POST,
                                 user_ip=get_real_ip(self.request))
        if form.is_valid():
            email.send_contact_email(form.cleaned_data)
            return self.render_to_response({})
        else:
            return self.render_to_response({'form': form})


class FeedbackView(TemplateResponseMixin, View):
    """
    Feedback form
    """
    template_name = "website/feedback.html"

    def get(self, *args, **kwargs):
        form = forms.FeedbackForm(user_ip=get_real_ip(self.request))
        return self.render_to_response({'form': form})

    def post(self, *args, **kwargs):
        form = forms.FeedbackForm(self.request.POST,
                                  user_ip=get_real_ip(self.request))
        if form.is_valid():
            email.send_feedback_email(form.cleaned_data)
            return self.render_to_response({})
        else:
            return self.render_to_response({'form': form})


class PrivacyPolicyView(TemplateResponseMixin, View):
    """
    Privacy policy page
    """
    template_name = "website/privacy.html"

    def get(self, *args, **kwargs):
        return self.render_to_response({})


class TermsConditionsView(TemplateResponseMixin, View):
    """
    Terms & Conditions page
    """
    template_name = "website/tc.html"

    def get(self, *args, **kwargs):
        return self.render_to_response({})


class TeamView(TemplateResponseMixin, View):
    """
    Team page
    """
    template_name = "website/team.html"

    def get(self, *args, **kwargs):
        return self.render_to_response({})


class LoginView(ContextMixin, TemplateResponseMixin, View):
    """
    Login page
    """
    template_name = "website/login.html"

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        context['next'] = self.request.POST.get(
            'next', self.request.GET.get('next', ''))
        return context

    def _redirect_after_login(self, user):
        if user.role == 'administrator':
            url = reverse('admin:index')
        elif user.role == 'merchant':
            url = reverse('website:devices')
        elif user.role == 'controller':
            url = reverse('website:merchant_list')
        else:
            url = reverse('website:landing')
        return redirect(url)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated():
            return self._redirect_after_login(self.request.user)
        context = self.get_context_data(**kwargs)
        context['form'] = forms.AuthenticationForm
        return self.render_to_response(context)

    def post(self, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        form = forms.AuthenticationForm(self.request, data=self.request.POST)
        if form.is_valid():
            user = form.get_user()
            login(self.request, user)
            return self._redirect_after_login(user)
        context['form'] = form
        return self.render_to_response(context)


class LogoutView(View):
    """
    Logout
    """
    def get(self, *args, **kwargs):
        logout(self.request)
        return redirect(reverse('website:landing'))


class ResetPasswordView(TemplateResponseMixin, View):
    """
    Reset password page
    """
    template_name = "website/reset_password.html"

    def get(self, *args, **kwargs):
        form = forms.ResetPasswordForm()
        return self.render_to_response({'form': form})

    def post(self, *args, **kwargs):
        form = forms.ResetPasswordForm(self.request.POST)
        if form.is_valid():
            form.set_new_password()
            return self.render_to_response({})
        else:
            return self.render_to_response({'form': form})


class RegistrationView(TemplateResponseMixin, View):
    """
    Registration page
    """
    template_name = "website/registration.html"

    def get(self, *args, **kwargs):
        if hasattr(self.request.user, 'merchant'):
            return redirect(reverse('website:devices'))
        form = forms.MerchantRegistrationForm()
        return self.render_to_response({'form': form})

    def post(self, *args, **kwags):
        form = forms.MerchantRegistrationForm(self.request.POST)
        if not form.is_valid():
            return self.render_to_response({'form': form})
        merchant = form.save()
        email.send_registration_info(merchant)
        login(self.request, merchant.user)
        return redirect(reverse('website:devices'))


class ActivationWizard(CookieWizardView):
    """
    Activate device and login
    """
    template_name = 'website/activation.html'
    form_list = [
        forms.DeviceActivationForm,
        forms.LoginMethodForm,
        forms.AuthenticationForm,
        forms.MerchantRegistrationForm,
    ]

    def show_login_form_condition(self):
        data = self.get_cleaned_data_for_step('1') or {}
        return data.get('method') == 'login'

    def show_registration_form_condition(self):
        data = self.get_cleaned_data_for_step('1') or {}
        return data.get('method') == 'register'

    condition_dict = {
        '2': show_login_form_condition,
        '3': show_registration_form_condition,
    }

    def dispatch(self, *args, **kwargs):
        if get_current_merchant(self.request):
            return redirect(reverse('website:activate_device'))
        return super(ActivationWizard, self).dispatch(*args, **kwargs)

    @atomic
    def done(self, form_list, **kwargs):
        # Get device
        device = form_list[0].device
        # Get merchant
        if self.show_login_form_condition():
            merchant = form_list[2].get_user().merchant
        elif self.show_registration_form_condition():
            merchant = form_list[2].save()
            email.send_registration_info(merchant)
        # Start activation
        activation.start(device, merchant)
        # Login & redirect
        login(self.request, merchant.user)
        return redirect(reverse('website:device_activation',
                                kwargs={'device_key': device.key}))


def get_current_merchant(request):
    if not hasattr(request.user, 'merchant'):
        return None
    return request.user.merchant


class MerchantCabinetView(ContextMixin, View):
    """
    Base class for merchant cabinet views
    """

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.merchant = get_current_merchant(request)
        if not self.merchant:
            raise Http404
        return super(MerchantCabinetView,
                     self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(MerchantCabinetView,
                        self).get_context_data(**kwargs)
        context['cabinet_page'] = resolve(self.request.path_info).url_name
        context['merchant'] = self.merchant
        return context


class DeviceListView(TemplateResponseMixin, MerchantCabinetView):
    """
    Device list page
    """
    template_name = 'cabinet/merchant/device_list.html'

    def get(self, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['devices'] = self.merchant.device_set.order_by('-id')
        return self.render_to_response(context)


class ActivationView(MerchantCabinetView):

    def dispatch(self, request, *args, **kwargs):
        self.merchant = get_current_merchant(request)
        if not self.merchant:
            try:
                self.merchant = models.MerchantAccount.objects.get(
                    activation_code__iexact=self.kwargs.get('merchant_code'))
            except models.MerchantAccount.DoesNotExist:
                raise Http404
        return super(MerchantCabinetView, self).dispatch(request, *args, **kwargs)


class ActivateDeviceView(TemplateResponseMixin, ActivationView):

    template_name = 'cabinet/merchant/activation.html'

    def get_context_data(self, **kwargs):
        context = super(ActivateDeviceView, self).get_context_data(**kwargs)
        context['activation_url'] = construct_absolute_url(
            'website:activate_device_nologin',
            kwargs={'merchant_code': self.merchant.activation_code})

xbterminal/website/templates/website/_registration_form_layout.html
{% load bootstrap3 i18n %}

<div class="row">
    <div class="col-md-6">{% bootstrap_field form.contact_first_name %}</div>
    <div class="col-md-6">{% bootstrap_field form.contact_last_name %}</div>
</div>
<div class="row">
    <div class="col-md-6">{% bootstrap_field form.contact_email %}</div>
</div>
<div class="row">
    <div class="col-md-6">{% bootstrap_field form.company_name %}</div>
    <div class="col-md-6">{% bootstrap_field form.trading_name %}</div>
</div>
<div class="row">
    <div class="col-md-6">{% bootstrap_field form.contact_phone %}</div>
</div>
{% bootstrap_field form.business_address %}
{% bootstrap_field form.business_address1 %}
<div class="row">
    <div class="col-md-6">{% bootstrap_field form.town %}</div>
    <div class="col-md-6">{% bootstrap_field form.post_code %}</div>
</div>
<div class="row">
    <div class="col-md-6">{% bootstrap_field form.county %}</div>
    <div class="col-md-6">{% bootstrap_field form.country %}</div>
</div>
<div class="form-group text-center">
    {% bootstrap_field form.terms %}
</div>

xbterminal/website/templates/website/activation.html
{% extends 'website/base.html' %}
{% load bootstrap3 i18n %}

{% block website_content %}
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h3>
            {% if wizard.steps.current == '0' %}{% trans 'Module activation' %}
            {% elif wizard.steps.current == '1' %}{% trans 'Choose how to login' %}
            {% elif wizard.steps.current == '2' %}{% trans 'Merchant login' %}
            {% elif wizard.steps.current == '3' %}{% trans 'Merchant registration' %}
            {% endif %}
        </h3>
        <form id="activation-wizard" action="" method="POST" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {{ wizard.management_form }}
            {% if wizard.steps.current == '3' %}
                {% include 'website/_registration_form_layout.html' %}
            {% else %}
                {% bootstrap_form wizard.form %}
            {% endif %}
            <div class="row">
                <div class="col-md-6">
                    <button type="submit" class="btn btn-default pull-right" value="">
                        {% trans 'Continue' %}
                    </button>
                </div>
                <div class="col-md-6">
                    {% if wizard.steps.prev %}
                    <button name="wizard_goto_step" type="submit" class="btn btn-default" value="{{ wizard.steps.prev }}">
                        {% trans 'Back' %}
                    </button>
                    {% else %}
                    <a href="{% url 'website:landing' %}" class="btn btn-default">
                        {% trans 'Cancel' %}
                    </a>
                    {% endif %}
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

xbterminal/website/templates/website/base.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/website.css' %}">
{% endblock %}

{% block content %}
<div class="content row">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                {% block website_content %}{% endblock %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

xbterminal/website/templates/website/contact.html
{% extends "website/base.html" %}
{% load bootstrap3 staticfiles i18n %}

{% block website_content %}
<div class="row">
    <div class="col-md-6">
        {% if form %}
        <h3>{% trans 'By email' %}</h3>
        <form id="contact-form" role="form" action="{% url 'website:contact' %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-default">{% trans 'Send' %}</button>
            <img id="loading-image" src="{% static 'img/loading.gif' %}">
        </form>
        {% else %}
        {% blocktrans %}<h3>Thanks!</h3><p class="lead">We will contact you as soon as possible</p>{% endblocktrans %}
        {% endif %}
    </div>
    {% if form %}
    <div class="col-md-6" id="contact-info">
        <h3>{% trans 'By phone' %}</h3>
        <p class="large">
            +44 (0) 20 8123 8185 <br>
            <small>{% trans 'during business hours London time' %}</small>
         </p>
        <h3>{% trans 'By post' %}</h3>
        <p class="large">
            {% trans 'Our registered address is'%}:<br>
            XBTerminal Ltd<br>
            71-75 Shelton Street<br>
            Covent Garden, London<br>
            WC2H 9JQ
        </p>
        <h3>{% trans 'By foot' %}</h3>
        <p class="large">
            {% trans "We're often can be found at" %}:<br>
            XBTerminal Ltd<br>
            Level39, One Canada Square<br>
            Canary Wharf, London<br>
            E1 5AB
        </p>
    </div>
    {% endif %}
</div>
{% endblock %}

xbterminal/website/templates/website/feedback.html
{% extends "website/base.html" %}
{% load bootstrap3 staticfiles i18n %}

{% block website_content %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        {% if form %}
        <h3>{% trans 'Feedback' %}</h3>
        <form id="feedback-form" role="form" action="{% url 'website:feedback' %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="row">
                <div class="col-md-6"><button type="submit" class="btn btn-default pull-right">{% trans 'Send' %}</button></div>
            </div>
        </form>
        {% else %}
        {% blocktrans %}<h3>Thanks!</h3><p class="lead">We will contact you as soon as possible</p>{% endblocktrans %}
        {% endif %}
    </div>
</div>
{% endblock %}

xbterminal/website/templates/website/landing.html
{% extends 'base.html' %}
{% load staticfiles i18n %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/landing.css' %}">
{% endblock %}

{% block js %}
<script src="{% static 'lib/scrollspy.js' %}"></script>
<script src="{% static 'lib/skrollr.min.js' %}"></script>
<script src="{% static 'js/landing.js' %}"></script>
{% endblock %}

{% block content %}
<div class="content row">
    <div
        class="image-section"
        id="about-section"
        data-0-start="background-position: center -400px;"
        data-0-top-bottom="background-position: center 200px;"
    >
        <div class="container">
            <div class="row">
                <div class="col-md-6" id="about-image">
                    <div class="section-image-wrapper">
                        <img src="{% static 'img/l_about.png' %}" alt="image">
                    </div>
                </div>
                <div class="col-md-6" id="about-text">
                    <span id="about-line1">{% trans 'meet the future' %}</span>
                    <span id="about-line2">{% trans 'of bitcoin point of sale' %}</span>
                </div>
            </div>
        </div>
    </div>
    <div class="text-section">
        <div class="container">
            <h2>{% trans 'Bitcoin payments made easy.' %}</h2>
            <h3>{% trans 'XBTerminal is the fast, simple and cost effective way for your business to start accepting bitcoin today.' %}</h3>
            <p class="large">
                {% blocktrans %}
                Our unique and innovative solutions allow you accept Bitcoin in a safe and risk free way. You are in control
                of the payment process whether you want to keep the Bitcoins or receive local currency. Through our seamless
                payment gateway integration we can <b>guarantee</b> a local currency return back to your business bank account.
                {% endblocktrans %}
            </p>
        </div>
    </div>
    <div
        class="image-section"
        id="mobile-section"
        data-0-bottom-top="background-position: center -800px;"
        data-0-top-bottom="background-position: center 200px;"
    >
        <div class="container">
            <div id="mobile-image">
                <div class="section-image-wrapper">
                    <img src="{% static 'img/l_mobile.png' %}" alt="image">
                </div>
            </div>
        </div>
    </div>
    <div class="text-section">
        <div class="container">
            <h2>{% trans 'XBT Mobile' %}</h2>
            <h3>{% trans 'XBT Mobile allows you to Start Accepting Bitcoin now with no upfront costs and the same great features as our dedicated hardware.' %}</h3>
            <p class="large">
                {% blocktrans %}
                Our mobile app is just as easy to operate as our hardware product. Customers may pay from any mobile
                Bitcoin wallet by NFC (Android only) or QR code, payment from offline mobile devices is supported by
                Bluetooth (Android only). The payment process is fast and secure, replicating the features of our
                dedicated hardware allowing you to dip your toe into the Bitcoin world without any upfront costs.
                This solution best suits merchants without a fixed point of sale like pop-up or street traders, it’s
                also a great starting point before deciding if you want a dedicated device for your business.
                {% endblocktrans %}
            </p>
            <div class="row" id="mobile-downloads">
                <div class="col-md-6" id="mobile-app-store">
                    <a href="{% url 'website:ios_app' %}" target="_blank"><img src="{% static 'img/app_store.png' %}"></a>
                </div>
                <div class="col-md-6" id="mobile-google-play">
                    <a href="{% url 'website:android_app' %}" target="_blank"><img src="{% static 'img/google_play.png' %}"></a>
                </div>
            </div>
        </div>
    </div>
    <div id="social">
        <a href="https://twitter.com/xbterminal" target="_blank"><img src="{% static 'img/soc_twitter.png' %}" alt="twitter"></a>
        <a href="https://www.facebook.com/xbterminal.io" target="_blank"><img src="{% static 'img/soc_facebook.png' %}" alt="facebook"></a>
        <a href="https://plus.google.com/100832480161765194207/about" target="_blank"><img src="{% static 'img/soc_google.png' %}" alt="google"></a>
    </div>
</div>
{% endblock %}

xbterminal/website/templates/website/login.html
{% extends "website/base.html" %}
{% load bootstrap3 staticfiles i18n %}

{% block website_content %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <form id="login-form" role="form" action="{% url 'website:login' %}" method="POST">
            <h3>{% trans 'Merchant login' %}</h3>
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="hidden" name="next" value="{{ next }}">
            <a href="{% url 'website:reset_password' %}">{% trans 'Forgot password?' %}</a>
            <div class="row">
                <div class="col-md-6"><button type="submit" class="btn btn-default pull-right">{% trans 'Login' %}</button></div>
                <div class="col-md-6"><a href="{% url 'website:landing' %}" class="btn pull-left">{% trans 'Cancel' %}</a></div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

xbterminal/website/templates/website/registration.html
{% extends "website/base.html" %}
{% load bootstrap3 i18n %}

{% block website_content %}
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="clearfix">
            <h3 class="pull-left">{% trans 'Merchant registration' %}</h3>
        </div>
        <form id="merchant-form" role="form" action="{% url 'website:registration' %}" method="POST">
            {% csrf_token %}
            {% include 'website/_registration_form_layout.html' %}
            <div class="row">
                <div class="col-md-6">
                    <button type="submit" class="btn btn-default pull-right">{% trans 'Submit' %}</button>
                </div>
                <div class="col-md-6">
                    <a href="{% url 'website:landing' %}" class="btn pull-left">{% trans 'Cancel' %}</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

xbterminal/website/templates/website/reset_password.html
{% extends "website/base.html" %}
{% load bootstrap3 i18n %}

{% block website_content %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        {% if form %}
        <h3>{% trans 'Reset password' %}</h3>
        <form id="reset-password-form" role="form" action="{% url 'website:reset_password' %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="row">
                <div class="col-md-6"><button type="submit" class="btn btn-default pull-right">{% trans 'Submit' %}</button></div>
                <div class="col-md-6"><a href="{% url 'website:landing' %}" class="btn pull-left">{% trans 'Cancel' %}</a></div>
            </div>
        </form>
        {% else %}
        {% blocktrans %}<p>New password has been sent to your email</p>{% endblocktrans %}
        {% endif %}
    </div>
</div>
{% endblock %}